apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dkf-core--deploykf-istio-gateway
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: deploykf-istio-gateway
    app.kubernetes.io/component: deploykf-core
    app.kubernetes.io/part-of: deploykf
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: "https://github.com/yankcrime/kubeflow-deploy.git"
    targetRevision: "main"
    path: "generated/manifests/deploykf-core/deploykf-istio-gateway"
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values-overrides.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "deploykf-istio-gateway"
