apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploykf-app-of-apps
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: deploykf-app-of-apps
    app.kubernetes.io/part-of: deploykf
spec:
  project: "default"
  source:
    repoURL: "https://github.com/yankcrime/kubeflow-deploy.git"
    targetRevision: "main"
    path: "generated/argocd"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"