apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kf-tools--volumes--volumes-web-app
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: volumes-web-app
    app.kubernetes.io/component: kubeflow-tools
    app.kubernetes.io/part-of: deploykf
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: "https://github.com/yankcrime/kubeflow-deploy.git"
    targetRevision: "main"
    path: "generated/manifests/kubeflow-tools/volumes/volumes-web-app"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeflow
